# Generated by Django 4.1.7 on 2023-03-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_client", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movements",
            old_name="client",
            new_name="name",
        ),
    ]
