# Generated by Django 4.1.7 on 2023-03-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_client", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderin",
            name="CtaCte",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="CtaCte",
        ),
        migrations.AlterField(
            model_name="movements",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="movements",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name="CtaCte",
        ),
        migrations.DeleteModel(
            name="OrderIn",
        ),
        migrations.DeleteModel(
            name="Payments",
        ),
    ]
